apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
# has to be in base64. Can use this cmd: echo -n 'username' | base64
  mongo-root-username: dXNlcm5hbWU=
  mongo-root-password: cGFzc3dvcmQ=