#!/usr/bin/env groovy

// @Library('jenkins-shared-library') // Global shared library defined in Jenkins

// project-scoped shared library instead of Global. Config is similiar to Jenkins UI
library identifier: 'jenkins-shared-library@main', retriever: modernSCM(
    [$class: 'GitSCMSource',
    remote: 'https://github.com/Cristian-Baeza/jenkins-shared-library',
    credentialsId: 'github-credentials'])

def gv

pipeline {   
    agent any
    tools {
        maven 'maven-3.9'
    }
    stages {
        stage("init") {
            steps {
                script {
                    gv = load "script.groovy"
                }
            }
        }
        stage("build jar") {
            steps {
                script {
                    buildJar() // references function in shared library repo
                }
            }
        }

        stage("build and push image") {
            steps {
                script {
                    buildImage 'cbaeza1/demo-app:jma-3.0' // references function in shared library repo
                    dockerLogin()
                    dockerPush 'cbaeza1/demo-app:jma-3.0'
                }
            }
        }

        stage("deploy") {
            steps {
                script {
                    gv.deployApp()
                }
            }
        }               
    }
} 
